const CATEGORY_ROW_COUNTS = Object.freeze({
  VS: 36,
  FE: 80,
  LW: 36,
  ST: 36,
  EL: 36,
});

const CATEGORY_ORDER = Object.freeze(Object.keys(CATEGORY_ROW_COUNTS));
const EXPECTED_ROW_COUNT = Object.values(CATEGORY_ROW_COUNTS).reduce(
  (sum, count) => sum + count,
  0
);
const FE_C02_REQUIREMENT_CONTRACT_DIGEST =
  "e81f47807371f1d565d66c1943e040066d982a9c271e18426926766502e27b5c";
const FE_A01_REQUIREMENT_CONTRACT_DIGEST =
  "b3c1124596fb625f3c43411528f1f8c207437df70d010a135405cedd155b4dc0";
const FE_C07_REQUIREMENT_CONTRACT_DIGEST =
  "07894f1b8f3793886569afcaa25dc2ef6279c75916f6959ac6ae3106c7541641";
const VS08_VALIDATED_WORKSHEET_REQUIREMENT_DIGEST =
  "551fec927295e447f187e43d19978682511767faacb5a3576326b7e0b67c2771";
const PRODUCT_PROFILE = Object.freeze({
  id: "CUSTOMER_CORE_5_V101_SPECIALIZED_QUALIFICATION_REPLAY",
  comparisonContractId:
    "PACKAGE_FIRST_QUALIFIED_INCLUSION_ABSENCE_LW20_EQUALITY_FIRE_DEFINITION_VS15_QUALIFIER_VS08_CONSENSUS_OBJECT_FAMILY_ANY_IDENTITY_AMOUNT_LOCAL_CONDITION_VS21_COST_ROLE_BINDING_GROUP_FIELDS_LIMIT_PORTFOLIO_REVIEW_GATE_VS22_LOCAL_WASTE_SCOPE_EXACT_CLAUSE_CODE_FIELD_GOVERNOR_HAZARDOUS_WASTE_PORTFOLIO_HARDENED_VS24_OPTIONAL_LOCAL_LIMIT_EXACT_SCOPE_IDENTITY_GLASS_SCAFFOLDING_COST_EQUALITY_CUSTOMER_REPLAY_VALIDATION_PROOF_LIMIT_LANGUAGE_GATE_VS25_SUM_EQUALIZATION_PRECISION_COMBINED_SCOPE_HEADING_PRECISION_AMOUNT_RECONCILIATION_RELATIVE_LIMIT_PORTFOLIO_TYPED_LIMIT_BASIS_CUSTOMER_REPLAY_SOURCE_BINDING_SUM_EQUALIZATION_TERMINAL_LOCAL_BASIS_BINDING_SOURCE_PROOF_PERCENT_DOCUMENT_BASIS_VS36_SYMBOLIC_LIMITS_EXACT_EVENT_LIMIT_LIST_ITEM_FE_A05_NESTED_LIST_CONTINUATION_PROOF_SOURCE_BOUND_OBJECT_SCOPE_EVIDENCE_INTERNAL_SCOPE_PROVENANCE_SELECTED_SCOPE_REPLAY_FE_C02_CONDITION_SCOPE_DECISION_QUALIFICATION_REPLAY_VS08_WORKSHEET_TRUST_ANCHOR_FE_A01_FE_C07_SOURCE_BOUND_QUALIFICATION_REPLAY_V62",
  categoryViews: CATEGORY_ORDER,
  categoryRowCounts: CATEGORY_ROW_COUNTS,
  categoryCatalogIds: Object.freeze({
    VS: "vs-occurrence-full-draft-v0.16",
    FE: "fe-occurrence-full-draft-v0.21",
    LW: "lw-occurrence-full-draft-v0.10",
    ST: "st-occurrence-full-draft-v0.6",
    EL: "el-occurrence-full-draft-v0.8",
  }),
  trustAnchors: Object.freeze({
    feA01ValidatedWorksheetRequirementV1: FE_A01_REQUIREMENT_CONTRACT_DIGEST,
    feC02ValidatedWorksheetRequirementV1: FE_C02_REQUIREMENT_CONTRACT_DIGEST,
    feC07ValidatedWorksheetRequirementV1: FE_C07_REQUIREMENT_CONTRACT_DIGEST,
    vs08ValidatedWorksheetRequirementV1:
      VS08_VALIDATED_WORKSHEET_REQUIREMENT_DIGEST,
  }),
  expectedRowCount: EXPECTED_ROW_COUNT,
});

module.exports = {
  CATEGORY_ORDER,
  CATEGORY_ROW_COUNTS,
  EXPECTED_ROW_COUNT,
  FE_A01_REQUIREMENT_CONTRACT_DIGEST,
  FE_C02_REQUIREMENT_CONTRACT_DIGEST,
  FE_C07_REQUIREMENT_CONTRACT_DIGEST,
  PRODUCT_PROFILE,
  VS08_VALIDATED_WORKSHEET_REQUIREMENT_DIGEST,
};
